name: "Plarix - LLM Cost Estimator"
description: "Estimate PR LLM cost impact (OpenAI + Anthropic) using bundled pricing. No AI calls, no telemetry."
author: "aegix-ai"
branding:
  icon: "dollar-sign"
  color: "green"

inputs:
  github_token:
    description: "Token with permission to read PR files and optionally comment (defaults to github.token)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Download plarix binary
      shell: bash
      run: |
        set -euo pipefail
        repo="${{ github.action_repository }}"
        ref="${{ github.action_ref }}"
        url="https://github.com/${repo}/releases/download/${ref}/plarix_Linux_x86_64.tar.gz"
        echo "Downloading ${url}"
        curl -sSfL "${url}" -o "${RUNNER_TEMP}/plarix.tar.gz"
        tar -xzf "${RUNNER_TEMP}/plarix.tar.gz" -C "${RUNNER_TEMP}"
        chmod +x "${RUNNER_TEMP}/plarix"
    - name: Run plarix
      shell: bash
      env:
        PLARIX_ACTION_PATH: ${{ github.action_path }}
        INPUT_TOKEN: ${{ inputs.github_token }}
        FALLBACK_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        if [ -n "$INPUT_TOKEN" ]; then
          export GITHUB_TOKEN="$INPUT_TOKEN"
        else
          export GITHUB_TOKEN="$FALLBACK_TOKEN"
        fi
        "${RUNNER_TEMP}/plarix"
