name: "Plarix - LLM Cost Estimator"
description: "Estimate PR LLM cost impact (OpenAI + Anthropic) using bundled pricing. No AI calls, no telemetry."
author: "aegix-ai"
branding:
  icon: "dollar-sign"
  color: "green"

inputs:
  version:
    description: "Release tag to download (defaults to the action ref, e.g. v0.2.0)"
    required: false
    default: ""
  github_token:
    description: "Token with permission to read PR files and optionally comment (defaults to github.token)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Download plarix binary
      shell: bash
      run: |
        set -euo pipefail
        action_path="${GITHUB_ACTION_PATH:-}"
        repo="${GITHUB_ACTION_REPOSITORY:-}"
        if [ -z "$repo" ] && [ -n "$action_path" ]; then
          # Expected shape: .../_actions/<owner>/<repo>/<ref>
          parent="$(dirname "$action_path")"
          repo_name="$(basename "$parent")"
          owner="$(basename "$(dirname "$parent")")"
          if [ -n "$owner" ] && [ -n "$repo_name" ]; then
            repo="${owner}/${repo_name}"
          fi
        fi
        repo="${repo:-aegix-ai/plarix-action}"

        version="${{ inputs.version }}"
        if [ -z "$version" ]; then
          version="${GITHUB_ACTION_REF:-}"
        fi
        if [ -z "$version" ] && [ -n "$action_path" ]; then
          version="$(basename "$action_path")"
        fi
        if [ -z "$version" ]; then
          version="v0"
        fi

        tmp="${RUNNER_TEMP}"

        urls=(
          "https://github.com/${repo}/releases/download/${version}/plarix_Linux_x86_64.tar.gz"
          "https://github.com/${repo}/releases/download/${version}/plarix-linux-amd64"
          "https://github.com/${repo}/releases/latest/download/plarix_Linux_x86_64.tar.gz"
          "https://github.com/${repo}/releases/latest/download/plarix-linux-amd64"
        )

        downloaded=""
        for url in "${urls[@]}"; do
          echo "Downloading ${url}"
          if curl -fsSL "${url}" -o "${tmp}/plarix.download"; then
            downloaded="${url}"
            break
          fi
        done
        if [ -z "$downloaded" ]; then
          echo "plarix-action: failed to download release asset from ${repo} (${version})" >&2
          exit 1
        fi

        if tar -xzf "${tmp}/plarix.download" -C "${tmp}" >/dev/null 2>&1; then
          chmod +x "${tmp}/plarix"
        else
          mv "${tmp}/plarix.download" "${tmp}/plarix"
          chmod +x "${tmp}/plarix"
        fi
    - name: Run plarix
      shell: bash
      env:
        PLARIX_ACTION_PATH: ${{ github.action_path }}
        INPUT_TOKEN: ${{ inputs.github_token }}
        FALLBACK_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        if [ -n "$INPUT_TOKEN" ]; then
          export GITHUB_TOKEN="$INPUT_TOKEN"
        else
          export GITHUB_TOKEN="$FALLBACK_TOKEN"
        fi
        "${RUNNER_TEMP}/plarix"
