name: "Plarix LLM cost"
description: "Estimate PR LLM cost impact and post a summary"
author: "aegix-ai"

inputs:
  github_token:
    description: "Token with permission to comment on PRs (defaults to GITHUB_TOKEN)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Download plarix binary
      shell: bash
      run: |
        set -euo pipefail
        REPO="${{ github.action_repository }}"
        if [ -z "$REPO" ]; then
          REPO="aegix-ai/plarix-action"
        fi
        curl -sSL "https://github.com/${REPO}/releases/latest/download/plarix_Linux_x86_64.tar.gz" -o /tmp/plarix.tar.gz
        tar -xzf /tmp/plarix.tar.gz -C /tmp
        chmod +x /tmp/plarix
    - name: Run plarix
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.github_token }}
        FALLBACK_TOKEN: ${{ github.token }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        set -euo pipefail
        if [ -n "$INPUT_TOKEN" ]; then
          export GITHUB_TOKEN="$INPUT_TOKEN"
        else
          export GITHUB_TOKEN="$FALLBACK_TOKEN"
        fi
        /tmp/plarix
