# Example: Release workflow for plarix-action maintainers
#
# This workflow is NOT included in the action repo (Marketplace requirement).
# Maintainers should run this in a separate CI repo or manually build releases.
#
# To build a release manually:
#   GOOS=linux GOARCH=amd64 go build -o plarix ./cmd/plarix
#   tar -czf plarix_Linux_x86_64.tar.gz plarix
#   # Upload plarix_Linux_x86_64.tar.gz to GitHub Release

name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o plarix ./cmd/plarix
          tar -czf plarix_Linux_x86_64.tar.gz plarix
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: plarix_Linux_x86_64.tar.gz
